In [8]:
# Let's import numpy library

import numpy as np

In [9]:
# Let's create numbers array

numbers = np.arange(start=0, stop=6, step=1).reshape(3, 2)

numbers

array([[0, 1],
       [2, 3],
       [4, 5]])

In [10]:
# Let's see transpose of this numbers

numbers.T

array([[0, 2, 4],
       [1, 3, 5]])

In [11]:
# Let's swap axes with swapaxes function

numbers.swapaxes(1, 0)

array([[0, 2, 4],
       [1, 3, 5]])

In [12]:
# Let's show AA^t

np.dot(numbers, numbers.T)

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])