In [11]:
# Let's create random numbers

import random

random_numbers = [random.randint(0, x) * x for x in range(100)]
random_numbers[0:10]

[0, 1, 4, 0, 8, 20, 36, 14, 8, 72]

In [12]:
# Let's convert random numbers to np array

import numpy as np

np_random_numbers = np.array(random_numbers)
np_random_numbers[0:10]

array([ 0,  1,  4,  0,  8, 20, 36, 14,  8, 72])

In [13]:
# Let's see dimentions of array

np_random_numbers.ndim

1

In [25]:
# Let's create a 2 dimensional array

dm_random_numbers = [ [ y * random.randint(0, x + 1) for y in range(10)] for x in range(40)]
dm_random_numbers[0:10]

[[0, 0, 2, 0, 0, 0, 6, 0, 0, 0],
 [0, 0, 2, 0, 4, 0, 6, 14, 0, 0],
 [0, 1, 4, 0, 4, 15, 12, 7, 8, 0],
 [0, 0, 2, 0, 12, 20, 0, 21, 8, 27],
 [0, 2, 4, 3, 20, 0, 0, 7, 32, 0],
 [0, 4, 12, 3, 16, 25, 18, 42, 8, 36],
 [0, 6, 2, 18, 12, 10, 0, 7, 24, 36],
 [0, 5, 6, 15, 0, 15, 48, 28, 16, 54],
 [0, 9, 14, 12, 36, 5, 12, 0, 64, 54],
 [0, 10, 0, 30, 16, 5, 24, 42, 72, 27]]

In [26]:
# Let's convert dm_random_numbers to numpy array

np_dm_random_numbers = np.array(dm_random_numbers)
np_dm_random_numbers.ndim

2

In [27]:
# Let's see shape of np_dm_random_numbers

np_dm_random_numbers.shape

(40, 10)

In [28]:
# Let's see size of np_dm_random_numbers

np_dm_random_numbers.size

400

In [38]:
# Let's use zeros function of numpy library

np_zeros = np.zeros((40, 10))
np_zeros[0:10]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [40]:
# Let's create np array with ones function

np_ones = np.ones((30,15))
np_ones[0:10]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [43]:
# Let's create array with arange function in np library

np_numbers = np.arange(2, 100, 4)
np_numbers

array([ 2,  6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58, 62, 66,
       70, 74, 78, 82, 86, 90, 94, 98])

In [46]:
# Let's use random module of np

np_rdim_numbers = np.random.rand(3, 2)
np_rdim_numbers

np_rint_numbers = np.random.randint(low=3, high=99,size=(50 , 9))
np_rint_numbers[:15]

array([[36, 19, 37, 97, 16, 90, 72,  5, 21],
       [19, 65, 39, 48, 84, 27, 59, 81,  3],
       [15, 69, 70, 16, 27, 52,  3, 23, 95],
       [86, 50, 75, 42, 47, 96, 48, 19, 68],
       [ 5, 60, 71, 90,  6, 56, 26, 97, 39],
       [ 9, 13, 15, 79, 68, 57, 93, 48, 77],
       [50, 21, 93, 18, 45, 77, 97, 41, 55],
       [18, 36, 45, 58, 92, 66, 59, 36, 92],
       [74, 55,  9, 26,  8,  5, 67, 79, 58],
       [41, 10, 63, 36, 31,  4, 38, 88, 98],
       [70, 36, 74, 49, 96, 13, 76, 47, 13],
       [84, 86, 43, 49, 29, 75, 16, 60, 58],
       [63, 47, 38, 31, 53, 53, 29, 96, 77],
       [38, 59, 40, 66, 11, 27, 37,  8, 51],
       [88, 53, 19, 74, 38, 36, 39, 49, 59]])

In [48]:
# Let's see full function of numpy library

np_full_numbers = np.full(shape=(32, 11), fill_value=5)
np_full_numbers[:10]

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [55]:
# Let's use eye and identity function

np_eye_numbers = np.eye(N=10, M=10)
print(np_eye_numbers)

np_identity_numbers = np.identity(5)
print(np_identity_numbers)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
