In [2]:
# Let's import numpy library

import numpy as np

In [3]:
# Let's create random numbers

np_numbers = np.arange(10, 100, 10)
np_numbers

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [4]:
# Let's cut some elements from array

np_sliced_numbers = np_numbers[3:5]
np_sliced_numbers

array([40, 50])

In [5]:
np_sliced_numbers[:] = np_sliced_numbers * 2

np_numbers

array([ 10,  20,  30,  80, 100,  60,  70,  80,  90])

In [6]:
# Let's use copy function

np_copy_numbers = np_numbers[0:3].copy()
np_copy_numbers

array([10, 20, 30])

In [7]:
np_copy_numbers[:] = np_copy_numbers / 10

np_copy_numbers

array([1, 2, 3])

In [8]:
# Let's see np_numbers

np_numbers

array([ 10,  20,  30,  80, 100,  60,  70,  80,  90])

In [9]:
# Let's work with dimensional array

dm_numbers = np.random.randint(low=0, high=9999, size=(9, 9))
dm_numbers

array([[1824,  238, 1631, 4706, 4798, 5283, 5027,  105, 9922],
       [6169, 1081, 7534, 5157, 8474, 2292, 5596, 5760, 3004],
       [ 975, 7357, 8424, 3058, 3961, 5271,   40, 6997, 2561],
       [2402, 4246, 6522, 8231, 2937, 7540, 7165, 4600, 9991],
       [9495, 7108, 6251, 7603, 1196, 5372, 3575, 7721, 4744],
       [4150, 7457, 2862,  500, 7228, 1020, 4465, 5295, 9867],
       [2475, 4197, 5975, 7600,  262, 9660, 6947, 6190, 3332],
       [   2, 8431, 3629, 7368, 3178, 9247,  291, 9837, 4298],
       [3708, 8668, 3066, 7476, 4387, 5159, 1959,  713, 2954]])

In [10]:
dm_numbers[1,1]

1081

In [11]:
# Let's cut top right corner

dm_numbers[:3, -3:]

array([[5027,  105, 9922],
       [5596, 5760, 3004],
       [  40, 6997, 2561]])

In [12]:
# Let's cut bottom right corner

dm_numbers[-4:,-4:]

array([[1020, 4465, 5295, 9867],
       [9660, 6947, 6190, 3332],
       [9247,  291, 9837, 4298],
       [5159, 1959,  713, 2954]])

In [13]:
# Let's cut top left corner

dm_numbers[:2, :2]

array([[1824,  238],
       [6169, 1081]])

In [14]:
# Let's cut bottom left corner

dm_numbers[-3:, :5]

array([[2475, 4197, 5975, 7600,  262],
       [   2, 8431, 3629, 7368, 3178],
       [3708, 8668, 3066, 7476, 4387]])

In [15]:
# Let's cut last column

dm_numbers[:, -1:]

array([[9922],
       [3004],
       [2561],
       [9991],
       [4744],
       [9867],
       [3332],
       [4298],
       [2954]])

In [16]:
# Let's cut first column

dm_numbers[:, :1]

array([[1824],
       [6169],
       [ 975],
       [2402],
       [9495],
       [4150],
       [2475],
       [   2],
       [3708]])

In [17]:
# Let's cut last two rows

dm_numbers[-2:, :]

array([[   2, 8431, 3629, 7368, 3178, 9247,  291, 9837, 4298],
       [3708, 8668, 3066, 7476, 4387, 5159, 1959,  713, 2954]])

In [22]:
# Let's create 3D array

randint_3d_numbers = np.random.randint(low=0, high=99, size=(5, 3, 5))
randint_3d_numbers

array([[[74, 12,  2, 83, 70],
        [64, 54, 97, 56, 90],
        [89, 30, 73, 89, 43]],

       [[86,  8, 71, 43, 65],
        [87, 28, 71, 19, 14],
        [58, 37, 89, 39, 96]],

       [[12, 56, 48, 95, 78],
        [ 7, 79, 83, 74, 39],
        [34, 49, 59, 17, 25]],

       [[ 6, 43, 58, 47, 74],
        [58, 87, 16, 47, 68],
        [84, 28, 42, 75, 59]],

       [[ 6, 84, 30, 14, 46],
        [54, 86, 78, 18, 83],
        [85,  1, 35, 42,  6]]])

In [32]:
# Let's create 3D array with full method

np_3d_numbers = np.array([
    [
        [0, 1, 2],
        [3, 4, 5],
        [6, 7, 8],
    ],
    [
        [9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
    ],
    [
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
    ],
])

np_3d_numbers

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [38]:
# Let's cut top left corner

np_3d_numbers[:2, :2, :2]

array([[[ 0,  1],
        [ 3,  4]],

       [[ 9, 10],
        [12, 13]]])

In [43]:
# Let's cut bottom right corner

np_3d_numbers[-2:, :, :2]

array([[[ 9, 10],
        [12, 13],
        [15, 16]],

       [[18, 19],
        [21, 22],
        [24, 25]]])

In [44]:
# Let's cut top left behind

np_3d_numbers[:2, -2:, -2:]

array([[[ 4,  5],
        [ 7,  8]],

       [[13, 14],
        [16, 17]]])

In [46]:
# Let's create array and cut left bottom behind

np_random_numbers = np.random.randint(low=1, high=100, size=(5, 4, 6))
np_random_numbers

array([[[57, 10, 58, 58, 44, 71],
        [30, 54, 54, 37, 99, 95],
        [96, 95, 57, 74, 35, 25],
        [15, 69, 13, 30, 29, 40]],

       [[93, 56,  2, 32, 48, 65],
        [47, 59, 96, 21, 43, 32],
        [99,  3, 20, 59, 68, 29],
        [50, 38,  2, 65, 20, 24]],

       [[38, 97, 27, 24, 10, 69],
        [12, 86,  2, 88, 43, 12],
        [ 3, 86, 17, 95, 46, 20],
        [12,  8, 51, 56, 36, 43]],

       [[14, 36, 54, 78, 17, 55],
        [36, 96, 61, 92, 45,  4],
        [25, 34, 75, 89, 74, 50],
        [12, 58, 32, 93, 30, 85]],

       [[52, 18, 92, 97, 86, 75],
        [12, 45, 11, 33, 11, 41],
        [43, 68, 32, 14, 78, 97],
        [48, 48, 10, 26, 43, 87]]])

In [47]:
# Let's cut it

np_random_numbers[-3:, :2, -3:]

array([[[24, 10, 69],
        [88, 43, 12]],

       [[78, 17, 55],
        [92, 45,  4]],

       [[97, 86, 75],
        [33, 11, 41]]])

In [55]:
# Let's cut middle of cube

np_random_numbers[1:-1, 1:-1, 2:-2]

array([[[96, 21],
        [20, 59]],

       [[ 2, 88],
        [17, 95]],

       [[61, 92],
        [75, 89]]])