In [1]:
# import numpy library

import numpy as np

In [2]:
users = np.array(
    [
        "sh.turg'unov",
        "m.tadjimatov",
        "y.valijonov",
        "n.abdulqaxxorov",
        "m.abdullayev",
        "d.jabborov",
        "a.jo'raboyev",
        "m.turgunova",
        "n.akmalovna",
        "a.mamajonov",
    ]
)

users

array(["sh.turg'unov", 'm.tadjimatov', 'y.valijonov', 'n.abdulqaxxorov',
       'm.abdullayev', 'd.jabborov', "a.jo'raboyev", 'm.turgunova',
       'n.akmalovna', 'a.mamajonov'], dtype='<U15')

In [22]:
statistics = np.random.randn(users.size, 7)

statistics

array([[ 1.27445785e+00,  1.39776515e+00, -1.25170708e-01,
         1.10361034e+00,  1.22114949e+00,  2.41470202e+00,
         1.05067834e+00],
       [-1.38529175e+00, -4.95262801e-01, -5.73917349e-02,
        -5.69687884e-01,  8.51235211e-01,  1.16170079e-01,
        -3.90270404e-01],
       [-2.15847169e-01,  2.19071370e+00,  1.30714131e+00,
        -6.37589905e-01, -1.09228454e+00, -6.03640296e-01,
        -3.72560937e-01],
       [ 1.61071657e+00, -2.68840170e-01,  6.55271008e-01,
         6.78212589e-01, -1.58764643e-01,  4.19377889e-01,
         8.49247364e-01],
       [ 8.04178767e-01, -6.02385118e-01,  6.58975614e-01,
        -1.09747813e+00,  7.34351704e-01,  9.12626305e-01,
         4.11066547e-01],
       [-8.41541477e-01,  8.84130185e-01,  5.92715314e-01,
         9.12930668e-01, -1.14455527e+00, -8.75640615e-01,
        -1.23996821e+00],
       [-2.29660380e+00, -1.44524796e+00,  3.42274607e-01,
        -6.50726932e-01, -1.39431997e+00, -1.01121326e+00,
         1.6809955

In [23]:
users == 'y.valijonov'

array([False, False,  True, False, False, False, False, False, False,
       False])

In [24]:
statistics[users == 'y.valijonov']

array([[-0.21584717,  2.1907137 ,  1.30714131, -0.6375899 , -1.09228454,
        -0.6036403 , -0.37256094]])

In [25]:
statistics[users=='y.valijonov', 1:-1]

array([[ 2.1907137 ,  1.30714131, -0.6375899 , -1.09228454, -0.6036403 ]])

In [26]:
mask = (users == 'y.valijonov') | (users == 'd.jabborov')

statistics[mask]

array([[-0.21584717,  2.1907137 ,  1.30714131, -0.6375899 , -1.09228454,
        -0.6036403 , -0.37256094],
       [-0.84154148,  0.88413019,  0.59271531,  0.91293067, -1.14455527,
        -0.87564062, -1.23996821]])

In [27]:
statistics[statistics < 0] = 0

statistics

array([[1.27445785, 1.39776515, 0.        , 1.10361034, 1.22114949,
        2.41470202, 1.05067834],
       [0.        , 0.        , 0.        , 0.        , 0.85123521,
        0.11617008, 0.        ],
       [0.        , 2.1907137 , 1.30714131, 0.        , 0.        ,
        0.        , 0.        ],
       [1.61071657, 0.        , 0.65527101, 0.67821259, 0.        ,
        0.41937789, 0.84924736],
       [0.80417877, 0.        , 0.65897561, 0.        , 0.7343517 ,
        0.9126263 , 0.41106655],
       [0.        , 0.88413019, 0.59271531, 0.91293067, 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.34227461, 0.        , 0.        ,
        0.        , 0.16809956],
       [0.86295616, 0.        , 0.81102809, 0.6719155 , 0.80506994,
        0.28711965, 0.3660722 ],
       [0.67509084, 0.0253388 , 0.        , 1.62632206, 1.58570493,
        1.02134866, 0.        ],
       [0.        , 0.        , 0.30727997, 1.68589765, 0.        ,
        0.25792502, 0. 