In [1]:
# Let's import numpy

import numpy as np

In [2]:
# Let's create array

numbers = np.arange(start=1, stop=10, step=1)
numbers

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Let's use sqrt

sqrt_numbers = np.sqrt(numbers)
sqrt_numbers

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [4]:
# Let's use square

square_numbers = np.square(numbers)
square_numbers

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [5]:
# Let's use exp

exp_numbers = np.exp(numbers)
exp_numbers

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [6]:
# Let's use log

log_numbers = np.log(numbers)
log_numbers

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [8]:
# Let's create actual numbers

actual_numbers = np.random.randn(9)
actual_numbers

array([ 0.82087531,  0.93412631,  1.03183502,  0.34147285,  2.31490572,
       -1.02411135,  0.14194259, -0.03755772, -0.43523157])

In [12]:
# Let's use modf function

residues, whole = np.modf(actual_numbers)

print(whole)
print(residues)

[ 0.  0.  1.  0.  2. -1.  0. -0. -0.]
[ 0.82087531  0.93412631  0.03183502  0.34147285  0.31490572 -0.02411135
  0.14194259 -0.03755772 -0.43523157]


In [18]:
# Let's use sign function

signed = np.sign(actual_numbers)
signed

array([ 1.,  1.,  1.,  1.,  1., -1.,  1., -1., -1.])

In [19]:
# Let's use isnan

isnan = np.isnan(actual_numbers)
isnan

array([False, False, False, False, False, False, False, False, False])

In [23]:
# Let's see binary function
# Let's use add function

added_numbers = np.add(numbers, actual_numbers)
added_numbers

array([1.82087531, 2.93412631, 4.03183502, 4.34147285, 7.31490572,
       4.97588865, 7.14194259, 7.96244228, 8.56476843])

In [24]:
numbers + actual_numbers

array([1.82087531, 2.93412631, 4.03183502, 4.34147285, 7.31490572,
       4.97588865, 7.14194259, 7.96244228, 8.56476843])

In [28]:
# Let's use multiply function

multiply_numbers = np.multiply(numbers, actual_numbers)
multiply_numbers

array([ 0.82087531,  1.86825262,  3.09550506,  1.36589141, 11.57452862,
       -6.14466811,  0.9935981 , -0.30046174, -3.91708413])

In [29]:
# Let's use maximum function

maximum_numbers = np.maximum(numbers, actual_numbers)
maximum_numbers

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])