In [14]:
# Let's import numpy

import numpy as np

In [15]:
# Let's create two array

yes_numbers = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
no_numbers = np.array([2.1, 2.2, 3.3, 4.4, 5.5])

In [16]:
# Let's use where function

condition = np.array([True, False, False, True, False])

result = np.where(condition, yes_numbers, no_numbers)
result

array([1.1, 2.2, 3.3, 1.4, 5.5])

In [17]:
# Let's work with dimensional array

r_numbers = np.random.randn(4, 4)
r_numbers

array([[ 0.56672361, -0.94726314,  0.63596632, -1.77515465],
       [ 0.34399381, -0.63215449, -0.64386631,  0.20810766],
       [-0.61582834, -1.40938828,  0.24945261, -1.05669456],
       [ 0.26424838,  0.25830736,  0.83446363, -0.88944477]])

In [18]:
# Now we can use where function

np.where(r_numbers<0,0,r_numbers * 100)

array([[56.67236098,  0.        , 63.59663163,  0.        ],
       [34.39938051,  0.        ,  0.        , 20.81076603],
       [ 0.        ,  0.        , 24.94526069,  0.        ],
       [26.42483815, 25.8307362 , 83.44636329,  0.        ]])