In [1]:
# Let's import numpy library

import numpy as np

In [2]:
first_numbers = np.arange(start=1, stop=7, step=1).reshape(2, 3)
second_numbers = np.arange(start=6, stop=12, step=1).reshape(2, 3)

In [3]:
first_numbers

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
second_numbers

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [7]:
# Let's add two arrays

first_numbers + second_numbers

array([[ 7,  9, 11],
       [13, 15, 17]])

In [8]:
# Let's multiply two arrays

first_numbers * second_numbers

array([[ 6, 14, 24],
       [36, 50, 66]])

In [9]:
# Let's divide two arrays

first_numbers / second_numbers

array([[0.16666667, 0.28571429, 0.375     ],
       [0.44444444, 0.5       , 0.54545455]])

In [10]:
# Let's use subtraction

first_numbers - second_numbers

array([[-5, -5, -5],
       [-5, -5, -5]])

In [11]:
first_numbers ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [12]:
first_numbers // 2

array([[0, 1, 1],
       [2, 2, 3]])

In [13]:
first_numbers % 2

array([[1, 0, 1],
       [0, 1, 0]])