In [1]:
# Let's import numpy

import numpy as np

In [6]:
# Let's generate random numbers

numbers = np.random.randint(low=1, high=10, size=(5, 4))
numbers

array([[9, 8, 5, 5],
       [4, 7, 7, 1],
       [3, 3, 5, 1],
       [2, 5, 9, 9],
       [6, 1, 7, 9]])

In [7]:
# Let's calculate total value of array

numbers.sum()

106

In [8]:
# Let's calculate total value of array by rows

numbers.sum(axis=1)

array([27, 19, 12, 25, 23])

In [10]:
# Let's calculate total value of array by columns

numbers.sum(axis=0)

array([24, 24, 33, 25])

In [12]:
# Let's get average of array

print(numbers.sum() / numbers.size)

numbers.mean()

5.3


5.3

In [14]:
# Let's see average of array by axis

print('Average by axis 1: ', numbers.mean(axis=1))

print('Average by axis 0: ', numbers.mean(axis=0))

Average by axis 1:  [6.75 4.75 3.   6.25 5.75]
Average by axis 0:  [4.8 4.8 6.6 5. ]


In [15]:
# Let's use cumsum function

numbers.cumsum()

array([  9,  17,  22,  27,  31,  38,  45,  46,  49,  52,  57,  58,  60,
        65,  74,  83,  89,  90,  97, 106])

In [16]:
# Let's see max value of array by axis

numbers.max(axis=1)

array([9, 7, 5, 9, 9])

In [17]:
# Let's see min value of array by axis

numbers.min(axis=0)

array([2, 1, 5, 1])

In [18]:
# Let's use cumprod function

numbers.cumprod()

array([            9,            72,           360,          1800,
                7200,         50400,        352800,        352800,
             1058400,       3175200,      15876000,      15876000,
            31752000,     158760000,    1428840000,   12859560000,
         77157360000,   77157360000,  540101520000, 4860913680000])