In [40]:
# Let's import numpy library

import numpy as np

In [41]:
numbers = np.random.randint(low=1, high=99, size=(4 ,7))

numbers

array([[88, 28, 88, 81, 37, 90, 44],
       [54, 33, 66, 44, 89, 53, 49],
       [34, 29, 49, 50, 58, 36, 42],
       [45, 28, 57, 77, 43,  5, 97]])

In [42]:
# Let's see sorted numbers

numbers.sort() # default axis is 0
numbers

array([[28, 37, 44, 81, 88, 88, 90],
       [33, 44, 49, 53, 54, 66, 89],
       [29, 34, 36, 42, 49, 50, 58],
       [ 5, 28, 43, 45, 57, 77, 97]])

In [43]:
# Let's sort by axises

numbers.sort(axis=1)
numbers

array([[28, 37, 44, 81, 88, 88, 90],
       [33, 44, 49, 53, 54, 66, 89],
       [29, 34, 36, 42, 49, 50, 58],
       [ 5, 28, 43, 45, 57, 77, 97]])

In [45]:
# Let's sort array by desc

reversed_numbers = -np.sort(-numbers)
reversed_numbers

array([[90, 88, 88, 81, 44, 37, 28],
       [89, 66, 54, 53, 49, 44, 33],
       [58, 50, 49, 42, 36, 34, 29],
       [97, 77, 57, 45, 43, 28,  5]])