In [1]:
# Let's import numpy

import numpy as np

In [2]:
numbers = np.random.randint(low=1, high=99, size=(8, 8))
numbers

array([[53, 26, 91, 53, 60, 73, 83, 31],
       [27, 58, 56, 57, 26, 58, 45, 11],
       [27, 69, 35, 70,  2, 90, 46, 89],
       [20,  1, 58, 56, 71, 16,  9, 17],
       [90, 55, 48, 84, 34, 54,  7,  4],
       [44, 63, 82, 15, 52, 62,  8, 63],
       [15, 21, 75, 76, 50, 16,  6, 39],
       [47, 92, 77,  7, 83, 28, 83, 69]])

In [3]:
np.save('random_numbers.npy', numbers)

In [4]:
random_numbers = np.load('random_numbers.npy')
random_numbers

array([[53, 26, 91, 53, 60, 73, 83, 31],
       [27, 58, 56, 57, 26, 58, 45, 11],
       [27, 69, 35, 70,  2, 90, 46, 89],
       [20,  1, 58, 56, 71, 16,  9, 17],
       [90, 55, 48, 84, 34, 54,  7,  4],
       [44, 63, 82, 15, 52, 62,  8, 63],
       [15, 21, 75, 76, 50, 16,  6, 39],
       [47, 92, 77,  7, 83, 28, 83, 69]])

In [5]:
s_numbers = np.random.rand(4, 9)
s_numbers

array([[0.11725472, 0.01236277, 0.83524528, 0.30447734, 0.35021647,
        0.52900716, 0.89805174, 0.95932049, 0.1823318 ],
       [0.64171136, 0.77360375, 0.68837805, 0.95315245, 0.51928127,
        0.32488907, 0.97015454, 0.89931497, 0.38263029],
       [0.03711058, 0.46143779, 0.88389168, 0.57767892, 0.9103957 ,
        0.44245109, 0.44306885, 0.24924697, 0.23804846],
       [0.51303044, 0.54593037, 0.68637858, 0.29929049, 0.39048233,
        0.15166068, 0.40047028, 0.80480043, 0.94733714]])

In [6]:
# Let's use savez function

np.savez('merged_numbers', first=numbers, second=s_numbers)

In [8]:
merged_numbers = np.load('merged_numbers.npz')

merged_numbers['first']

array([[53, 26, 91, 53, 60, 73, 83, 31],
       [27, 58, 56, 57, 26, 58, 45, 11],
       [27, 69, 35, 70,  2, 90, 46, 89],
       [20,  1, 58, 56, 71, 16,  9, 17],
       [90, 55, 48, 84, 34, 54,  7,  4],
       [44, 63, 82, 15, 52, 62,  8, 63],
       [15, 21, 75, 76, 50, 16,  6, 39],
       [47, 92, 77,  7, 83, 28, 83, 69]])

In [9]:
merged_numbers['second']

array([[0.11725472, 0.01236277, 0.83524528, 0.30447734, 0.35021647,
        0.52900716, 0.89805174, 0.95932049, 0.1823318 ],
       [0.64171136, 0.77360375, 0.68837805, 0.95315245, 0.51928127,
        0.32488907, 0.97015454, 0.89931497, 0.38263029],
       [0.03711058, 0.46143779, 0.88389168, 0.57767892, 0.9103957 ,
        0.44245109, 0.44306885, 0.24924697, 0.23804846],
       [0.51303044, 0.54593037, 0.68637858, 0.29929049, 0.39048233,
        0.15166068, 0.40047028, 0.80480043, 0.94733714]])

In [11]:
# Let's use savez_compressed

np.savez_compressed('compresed_numbers.npz', first=numbers, second=s_numbers)

In [12]:
compressed_numbers = np.load('compresed_numbers.npz')

compressed_numbers['first']

array([[53, 26, 91, 53, 60, 73, 83, 31],
       [27, 58, 56, 57, 26, 58, 45, 11],
       [27, 69, 35, 70,  2, 90, 46, 89],
       [20,  1, 58, 56, 71, 16,  9, 17],
       [90, 55, 48, 84, 34, 54,  7,  4],
       [44, 63, 82, 15, 52, 62,  8, 63],
       [15, 21, 75, 76, 50, 16,  6, 39],
       [47, 92, 77,  7, 83, 28, 83, 69]])

In [13]:
compressed_numbers['second']

array([[0.11725472, 0.01236277, 0.83524528, 0.30447734, 0.35021647,
        0.52900716, 0.89805174, 0.95932049, 0.1823318 ],
       [0.64171136, 0.77360375, 0.68837805, 0.95315245, 0.51928127,
        0.32488907, 0.97015454, 0.89931497, 0.38263029],
       [0.03711058, 0.46143779, 0.88389168, 0.57767892, 0.9103957 ,
        0.44245109, 0.44306885, 0.24924697, 0.23804846],
       [0.51303044, 0.54593037, 0.68637858, 0.29929049, 0.39048233,
        0.15166068, 0.40047028, 0.80480043, 0.94733714]])