In [1]:
# Let's import numpy library

import numpy as np

In [14]:
x = np.arange(1, 9).reshape((2, 4))
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
y = np.arange(5, 13).reshape((2, 4))
y

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
x + y

array([[ 6,  8, 10, 12],
       [14, 16, 18, 20]])

In [22]:
y - x

array([[4, 4, 4, 4],
       [4, 4, 4, 4]])

In [26]:
a = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

b = np.array([
   [9, 8, 7],
   [6 ,5 ,4],
])

np.dot(a, b)

array([[21, 18, 15],
       [51, 44, 37],
       [81, 70, 59]])

In [27]:
a.dot(b)

array([[21, 18, 15],
       [51, 44, 37],
       [81, 70, 59]])

In [28]:
np.dot(b, a)

array([[68, 92],
       [41, 56]])

In [29]:
b.dot(a)

array([[68, 92],
       [41, 56]])