In [55]:
# Let's import numpy library

import numpy as np

In [56]:
# Let's create random numbers

np_numbers = np.arange(10, 100, 10)
np_numbers

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [57]:
# Let's cut some elements from array

np_sliced_numbers = np_numbers[3:5]
np_sliced_numbers

array([40, 50])

In [58]:
np_sliced_numbers[:] = np_sliced_numbers * 2

np_numbers

array([ 10,  20,  30,  80, 100,  60,  70,  80,  90])

In [59]:
# Let's use copy function

np_copy_numbers = np_numbers[0:3].copy()
np_copy_numbers

array([10, 20, 30])

In [60]:
np_copy_numbers[:] = np_copy_numbers / 10

np_copy_numbers

array([1, 2, 3])

In [61]:
# Let's see np_numbers

np_numbers

array([ 10,  20,  30,  80, 100,  60,  70,  80,  90])

In [67]:
# Let's work with dimensional array

dm_numbers = np.random.randint(low=0, high=9999, size=(9, 9))
dm_numbers

array([[6989, 6709, 8493, 8658, 4627,  412, 3580, 4681, 1433],
       [4308, 2791, 4961, 6069, 9660, 5265, 6489, 2079, 8532],
       [4877, 4727,  629, 6825, 3162,  358, 8565, 9650, 4660],
       [8727, 3646,  119,  794, 6442, 6885, 2261, 1662, 9821],
       [9919, 4755, 6031, 6772, 7852, 5313, 4350, 9410, 4743],
       [6900, 2518, 9922, 9462, 2536, 2132, 2512, 6417, 5557],
       [4810,  139, 6672, 4758, 2545, 8851,  980, 8219, 6439],
       [ 470, 2012, 5465, 7548, 9938,  277, 3812, 5487, 5544],
       [2375, 8571, 6804, 9066, 8317,  515, 5785, 7999, 3722]])

In [69]:
dm_numbers[1,1]

2791

In [74]:
# Let's cut top right corner

dm_numbers[:3, -3:]

array([[3580, 4681, 1433],
       [6489, 2079, 8532],
       [8565, 9650, 4660]])

In [75]:
# Let's cut bottom right corner

dm_numbers[-4:,-4:]

array([[2132, 2512, 6417, 5557],
       [8851,  980, 8219, 6439],
       [ 277, 3812, 5487, 5544],
       [ 515, 5785, 7999, 3722]])

In [76]:
# Let's cut top left corner

dm_numbers[:2, :2]

array([[6989, 6709],
       [4308, 2791]])

In [78]:
# Let's cut bottom left corner

dm_numbers[-3:, :5]

array([[4810,  139, 6672, 4758, 2545],
       [ 470, 2012, 5465, 7548, 9938],
       [2375, 8571, 6804, 9066, 8317]])

In [79]:
# Let's cut last column

dm_numbers[:, -1:]

array([[1433],
       [8532],
       [4660],
       [9821],
       [4743],
       [5557],
       [6439],
       [5544],
       [3722]])

In [87]:
# Let's cut first column

dm_numbers[:, :1]

array([[6989],
       [4308],
       [4877],
       [8727],
       [9919],
       [6900],
       [4810],
       [ 470],
       [2375]])

In [88]:
# Let's cut last two rows

dm_numbers[-2:, :]

array([[ 470, 2012, 5465, 7548, 9938,  277, 3812, 5487, 5544],
       [2375, 8571, 6804, 9066, 8317,  515, 5785, 7999, 3722]])